export const successCompleteItemText = [
  "You're crushing it! Keep that momentum going!",
  "One step at a time - you've got this!",
  "Your progress is inspiring! Don't stop now!",
  'Every small victory counts. Celebrate this one!',
  "The only way to fail is to stop trying. And you're not stopping!",
  "Look how far you've come! That's amazing!",
  'Your dedication is paying off. Keep shining!',
  'Challenge accepted and conquered! Well done!',
  "Progress over perfection. You're making great strides!",
  "That's the spirit! Your determination is unstoppable!",
  "You're turning obstacles into opportunities. Incredible!",
  "The expert in anything was once a beginner. You're leveling up!",
  "Small progress is still progress. You're moving forward!",
  'Your future self is thanking you for this effort!',
  "That's another win for you! Collect them all!",
  "You're not just doing the work, you're mastering it!",
];

export const alreadyCompletedMotivations = [
  'Repetition is the mother of mastery! Reviewing completed tasks builds expertise.',
  'Well done revisiting this! True mastery comes from reinforcement.',
  "Knowledge grows deeper with review. You're building unshakable foundations!",
  'Revisiting completed work shows dedication to real understanding. Impressive!',
  "The mark of an expert is returning to fundamentals. You're on the right path!",
  "Every review session makes neural pathways stronger. You're upgrading your brain!",
  "Learning isn't linear. Revisiting completed topics reveals new insights!",
  "You're not repeating, you're deepening. Wisdom comes from layered understanding.",
  'The difference between good and great? Great learners revisit and refine.',
  'Mastery requires revisiting. Your commitment to excellence is inspiring!',
  "Smart learners reinforce success. You're building durable knowledge!",
  'Comfort with fundamentals enables advanced thinking. Keep strengthening your base!',
  'Returning to completed work shows intellectual maturity. Well done!',
  "Repetition with intention builds intuition. You're cultivating expertise!",
  "Reviewing is where familiarity becomes fluency. You're leveling up your skills!",
  "The best learners revisit. You're demonstrating elite learning habits!",
];
